<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261004183000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create courier table and link existing ROLE_COURIER users';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE courier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_COURIER_USER ON courier (user_id)');
        $this->addSql('ALTER TABLE courier ADD CONSTRAINT FK_COURIER_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        // Link existing users that already have ROLE_COURIER and no courier row yet
        $this->addSql(<<<'SQL'
            INSERT INTO courier (user_id)
            SELECT u.id
            FROM "user" u
            WHERE u.roles::text LIKE '%ROLE_COURIER%'
              AND NOT EXISTS (
                  SELECT 1 FROM courier c WHERE c.user_id = u.id
              )
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE courier DROP CONSTRAINT FK_COURIER_USER');
        $this->addSql('DROP TABLE courier');
    }
}
