<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261004190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create delivery_route and delivery_order tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE delivery_route (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, source_filename VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE delivery_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, route_id INT NOT NULL, position INT NOT NULL, client_name VARCHAR(255) NOT NULL, phone VARCHAR(64) DEFAULT NULL, address VARCHAR(512) NOT NULL, products JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DELIVERY_ORDER_ROUTE ON delivery_order (route_id)');
        $this->addSql('ALTER TABLE delivery_order ADD CONSTRAINT FK_DELIVERY_ORDER_ROUTE FOREIGN KEY (route_id) REFERENCES delivery_route (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE delivery_order DROP CONSTRAINT FK_DELIVERY_ORDER_ROUTE');
        $this->addSql('DROP TABLE delivery_order');
        $this->addSql('DROP TABLE delivery_route');
    }
}
